[[bond]]
source = "tpknam1qrsfm6ge4ufucs6ekhpeeqfrvum0ewj85u8zmk0h6dlw0gwppzlnv6x7u04"
validator = "tnam1q8azt2cpqmc6tr2gvg5v62e4jr0t9327yupaf595"
amount = "144.16"

[bond.signatures]
tpknam1qrsfm6ge4ufucs6ekhpeeqfrvum0ewj85u8zmk0h6dlw0gwppzlnv6x7u04 = "signam1qzg3rf4lzpsr9ff8r4t44htzfjxrx0pf5lxs3ej4fc030jlk7mx8e5v3szw8l3egytdwexyy0kgff6agywwext9ppx5h9tvdrck3rdgffz0auw"
